import Head from 'next/head'
import { useEffect } from 'react';
import styles from '../../styles/Home.module.css'

export default function Home() {
    useEffect(() => {
        window.location.replace("https://youtu.be/dQw4w9WgXcQ");
    },[]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
