import Head from 'next/head'
import { useEffect } from 'react';
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>รายละเอียด</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          รายละเอียดของ &quot;เทคโนโลยีสมัยนี้&quot; 
        </h1>

        <p className={styles.description}>
          การทำงานของ &quot;เทคโนโลยีสมัยนี้&quot; อาจจะมีความไม่ถูกต้องประมาณหนึ่ง 
          <br/>เนื่องจาก &quot;เทคโนโลยีสมัยนี้&quot; ไม่ได้มีความสามารถเท่ากับเทคโนโลยีสมัยใหม่
          <br/><br/>
          และเป็นการทำใน Stupid Hackaton จึงทำให้  &quot;เทคโนโลยีสมัยนี้&quot;  โง่ตามไปด้วย
          <br/>&quot;เทคโนโลยีสมัยนี้&quot; อาจฉลาดไม่พอจึงขอเวลาอีกไม่นานในการประมวลผล
          <br/><br/>
          ถึงแม้ว่า &quot;เทคโนโลยีสมัยนี้&quot; อาจจะไม่ได้คุณภาพมาก 
          <br/>แต่ 3  &quot;เทคโนโลยีสมัยนี้&quot;  ก็น้องๆเทคโนโลยีสมัยใหม่
          <br/><br/>
          หากผิดพลาดประการใดขอให้เป็นความผิดของ &quot;เทคโนโลยีสมัยนี้&quot;
        </p>

      </main>
    </div>
  )
}
