import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>&quot;เทคโนโลยีสมัยนี้&quot;</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ยินดีต้อนรับเข้าสู่ &quot;เทคโนโลยีสมัยนี้&quot; 
        </h1>

        <p className={styles.description}>
          เชิญชมสิ่งที่ทำได้ด้วย  &quot;เทคโนโลยีสมัยนี้&quot; 
        </p>

        <div className={styles.grid}>
        <Link href="/what-is-it">
          <a className={styles.card}>
            <h2>มันคืออะไร &rarr;</h2>
            <p>ด้วย &quot;เทคโนโลยีสมัยนี้&quot; สามารถทายรูปภาพได้</p>
          </a>
          </Link>

          <Link href="/is-it-ok">
          <a className={styles.card}>
            <h2>รูปนี้โอไม่โอ &rarr;</h2>
            <p>ด้วย &quot;เทคโนโลยีสมัยนี้&quot; สามารถบอกได้ว่ารูปนี้โอเคหรือไม่</p>
          </a>
          </Link>

          <Link href="/turtle-tattoo">
          <a className={styles.card}>
          
            <h2>สักลายเต่า &rarr;</h2>
            <p>ด้วย &quot;เทคโนโลยีสมัยนี้&quot; สามารถออกแบบลายเต่าได้</p>
          </a>
          </Link>

          <Link href="/detail">
          <a className={styles.card}>
          
            <h2>รายละเอียด &rarr;</h2>
            <p>ด้วย &quot;เทคโนโลยีสมัยนี้&quot; สามารถอธิบายรายละเอียดได้</p>
          </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
      <Link href="/vercel">
        <a
          target="_blank"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        </Link>
      </footer>
    </div>
  )
}
